### ISSUE TITLE
Feature request: play only rated songs from artist?

### ISSUE THREAD

**Issue by zeltak** [caleb531/play-song#59]
Hi again

the more i play around with this workflow i learn out how awesome it is.. :)

is it possible to tot add a feature request so that there could be a new command to  play only rated songs from artist? 

ie a user define threshold (rating >=4) and then only songs >=4 from artist plays?

thx a bunch!!

z

**Comment by caleb531** [comment]
That's a very specific feature request, and unfortunately, it's not something I would probably add for that reason. 

However, If you have any experience writing AppleScript, you are should be able to modify the workflow code yourself.

1. Right-click the workflow in the Workflows area of Alfred Preferences
2. Choose "Open in Finder" from the menu
3. Navigate into the `resources` folder
4. Open `config.applescript` in Script Editor (right-click > Open With...)
5. Locate the `getResultsFromQuery` function, which contains all of the internal calls to search for songs matching your query (this is used internally by `playartist`, too). You can probably add a condition like `and if rating >= 80` (`80` corresponds to 4 stars, because it's out of 100)

**Comment by zeltak** [comment]
thx!! I have zero coding experience but will play around with it tomorrow..where else am i gonna go ben locked up in NYC past 50 days ;-)

thx again!
