### ISSUE TITLE
Play album doesn't honour album order just playing order from "all songs"

### ISSUE THREAD

**Issue by sohate** [caleb531/play-song#62]
"Play album" doesn't honour an album's song order, just playing song order from "songs" library. Can you fix it?

**Comment by caleb531** [comment]
@sohate I actually used to always play albums in the album's song order. However, this required me to sort the album's songs on every request, which was an expensive operation. For large albums, it would take quite a bit of time.

To improve performance, I decided to honor whatever sorting was set by your Music library at the moment. If you sort your library (in the "Songs" view) by "Album" or "Album by Artist", then you will get the behavior you desire. But also, I do it this way so that if you want to play an album in order of Play Count or something, you could do so. There's a note about all this in the README.

**Comment by sohate** [comment]
Now I see, thanks! But still it is not obvious, and not so comfortable.

**Comment by caleb531** [comment]
@sohate I understand, but that's the way I've chosen to do things. But I appreciate the honest feedback, and hope that you're still able to make it work for you (even if it's not perfect 😅).
