### ISSUE TITLE
Playsong won't search my song

### ISSUE THREAD

**Issue by tujuhtigatujuh** [caleb531/play-song#69]
Hello, I'm uncertain as to why things aren't functioning as anticipated. Every time I attempt to play a song, the desired track isn't displayed in the results.

**Comment by caleb531** [comment]
@tujuhtigatujuh I'm sorry to hear the workflow isn't working for you, and I want to help—I just need to know a few more details:

1. What are you seeing instead of the desired song result? Does Alfred say "No Results Found", or are you seeing the fallback searches like "Google"? Or are you seeing no Alfred results for anything at all?
2. What system language do you have set?
3. What version of macOS are you using?

**Comment by tujuhtigatujuh** [comment]
1. No results found
2. English (US)
3. 14.0

Sent via Superhuman iOS ( ***@***.*** )

**Comment by tujuhtigatujuh** [comment]
I've discovered something; it only plays songs that are already in my library. It doesn't play any songs that haven't been added to my library yet. I believe it would be better if it could play any song, regardless of whether it's already in my library or not.

**Comment by caleb531** [comment]
@tujuhtigatujuh Yes, the workflow can only play music that you've already added to your library. The only exception is if the songs are part of an Apple Music playlist in your library (in which the playlist entry itself would be part of your library, but the individual songs don't have to be). In this case, you could use the `playplaylist` keyword to play the playlist.

I've explored adding the ability to play songs outside your library, but it would require Objective C / Swift to accomplish, which is really outside of my experience. So, at least for the time being, this is not something I intend to implement.

**Comment by tujuhtigatujuh** [comment]
I see, thanks!

Sent via Superhuman iOS ( ***@***.*** )
